apiVersion: v1
kind: ServiceAccount
metadata:
  name: operator
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: operator
rules:
- apiGroups:
    - ""
  resources:
    - pods
    - events
  verbs:
    - "list"
    - "watch"
    - "get"
    - "create"
    - "patch"
---
# Source: arms-prom-operator/templates/arms-controller-prom-clusterRoleBinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: operator
subjects:
  - kind: ServiceAccount
    name: operator
    namespace: kube-system
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  labels:
    app: operator
  name: operator
  namespace: kube-system
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: operator
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: operator
    spec:
      containers:
      - image: reg.docker.alibaba-inc.com/infrastore/test-operator:v0.6
        imagePullPolicy: IfNotPresent
        name: operator 
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccountName: operator
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        key: sigma.ali/resource-pool
        value: ackee_pool
      - effect: NoSchedule
        key: sigma.ali/is-ecs
        operator: Exists
