apiVersion: apps/v1 
kind: Deployment
metadata:
  labels:
    app: test-trace 
  name: test-trace-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-trace 
  template:
    metadata:
      annotations:
        catch-trace: enabled 
      labels:
        app: test-trace 
    spec:
      containers:
      - image: reg.docker.alibaba-inc.com/infrastore/nginx:1.15.1 
        imagePullPolicy: IfNotPresent
        name: test-trace 
        resources: 
          limits:
            memory: 10Mi
            cpu: 10m
      dnsPolicy: ClusterFirst
      tolerations:
      - operator: Exists
